/* eslint-disable @next/next/no-before-interactive-script-outside-document */
import Head from "next/head";
import Script from "next/script";

export default function Home({ publicEnv }) {
  return (
    <>
      <Head>
        <title>Plain Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Plain Next.js App, testing...</h1>
    </>
  );
}

export async function getServerSideProps({ req, res }) {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );
  return {
    props: {
      publicEnv: {
        randomName: global.process.env.APP_NAME || "plain-nextjs",
      },
    }, // will be passed to the page component as props
  };
}
