{{ if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "common.fullname" $ }}
                port:
                  number: {{ $.Values.ports.management }}
    {{- end }}
  tls:
    - secretName: {{ .Values.ingress.secretname }}
      hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . }}
      {{ end }}

{{- end }}
