---
apiVersion: v1
kind: Service

metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | indent 4 }}

spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.ports.http }}
    targetPort: {{ .Values.ports.http }}
